### ISSUE TITLE
Request to get new refreshToken is not working in GraphQL

### ISSUE THREAD

**Issue by anandkm629** [karprabha/localfluence#3]
### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

- Login into the app
- Wait for 15 min for the access token to get expired
- Refresh page to test refresh token fetching

### What is the expected behavior?

It should use the refreshToken route to get the new accessToken

### What do you see instead?

It fails the request and logouts the user

**Comment by karprabha** [comment]
Hi @anandkm629 ,
This has been fixed in patch 0.1.6
